sudo: false
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.5.0
  - jruby-9.1.9.0
before_install: gem install bundler -v 1.13.7
env:
  - JRUBY_OPTS="--debug"
